- sherpa/bin/conformer_rnnt/decode_manifest.py
- sherpa/bin/conformer_rnnt/offline_client.py
- sherpa/bin/conformer_rnnt/offline_server.py
- sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_client.py
- sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_server.py
- sherpa/bin/streaming_conformer_rnnt/streaming_server.py
- sherpa/bin/web/js/offline_record.js
- sherpa/bin/web/js/streaming_record.js
- sherpa/bin/web/js/upload.js
The websocket protocol is message-based and we can receive the message from the client in whole by a single call `socket.recv()`, which simplifies the code a lot.
> Simplify data receiving.

- .github/workflows/build-doc.yml
- .github/workflows/run-cpp-test.yaml
- sherpa/csrc/CMakeLists.txt
- sherpa/csrc/parse_options.cc
- sherpa/csrc/parse_options.h
- sherpa/csrc/test_parse_options.cc
The C++ code is copied/modifed from Kaldi so that users can use their existing kaldi-style config files to pass options
to sherpa in the future.
> Add fully kaldi-compatible parse-options.

- sherpa/bin/conv_emformer_transducer_stateless2/streaming_server.py
- sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_server.py
- sherpa/bin/pruned_transducer_statelessX/offline_server.py
- sherpa/bin/streaming_pruned_transducer_statelessX/streaming_server.py
See also
- https://github.com/pytorch/pytorch/issues/33354
- https://github.com/k2-fsa/sherpa/issues/90#issuecomment-1213367704
The following experiments show that we can decrease the waiting time of the first request by using warmup.
The client waits for about 6 seconds to get a reply after sending the data.
```
2022-08-22 13:08:37,472 INFO [streaming_client.py:88] Sending /ceph-fj/fangjun/open-source-2/icefall-models/icefall-asr-librispeech-p
runed-stateless-emformer-rnnt2-2022-06-01/test_wavs/1089-134686-0001.wav
2022-08-22 13:08:43,094 INFO [streaming_client.py:79] Partial result (last 20 words):
2022-08-22 13:08:43,153 INFO [streaming_client.py:79] Partial result (last 20 words): AFTER
2022-08-22 13:08:43,186 INFO [streaming_client.py:79] Partial result (last 20 words): AFTER EAR …
```
> add warmup for torchscript models

- .github/workflows/run-cpp-test.yaml
- cmake/cmake_extension.py
- cmake/kaldi_native_io.cmake
- setup.py
- sherpa/csrc/CMakeLists.txt
- sherpa/csrc/version.cc
- sherpa/csrc/version.h.in
Compile `kaldi_native_io` from source so that it uses the same cxx11 abi as the one used by PyTorch.
Note: Some versions of PyTorch are compiled with `-D_GLIBCXX_USE_CXX11_ABI=0` while some are with `-D_GLIBCXX_USE_CXX11_ABI=1`.  Compiling `kaldi-native-io` from source can avoid  issues caused by different ABI settings.
> Fix compiling with kaldi-native-io

- docs/source/python/streaming_asr/conformer/conformer_rnnt_for_Chinese/server.rst
- docs/source/python/streaming_asr/conformer/conformer_rnnt_for_English/server.rst
- docs/source/python/streaming_asr/conv_emformer/server.rst
- docs/source/python/streaming_asr/emformer/server.rst
- docs/source/python/streaming_asr/lstm/server.rst
so that rule3 for endpointing won't be activated in the web demo. (Its default value is 20, which may be too short for the web demo).
> Use a larger value for utterance length in endpointing for the web demo.

- sherpa/bin/pruned_transducer_statelessX/offline_client.py
- sherpa/bin/pruned_transducer_statelessX/offline_server.py
When the recognition result is an empty string,  `websocket.send("")` is a no-op (I guess).
As a result, the client will wait indefinitely.
This PR just sends `"<EMPTY>"` to the client so the client gets something and exits.
> Fix sending empty string to the client

- .github/workflows/run-streaming-conformer-test.yaml
- .github/workflows/run-streaming-conv-emformer-test.yaml
- .github/workflows/run-wenetspeech-streaming-conformer-rnnt-test.yaml
- sherpa/bin/conv_emformer_transducer_stateless2/beam_search.py
- sherpa/bin/conv_emformer_transducer_stateless2/streaming_server.py
- sherpa/bin/streaming_pruned_transducer_statelessX/beam_search.py
- sherpa/bin/streaming_pruned_transducer_statelessX/streaming_server.py
This PR adds the following : 
- Modified beam search to streaming transducer
> Add streaming modified beam search

- sherpa/bin/conv_emformer_transducer_stateless2/beam_search.py
- sherpa/bin/conv_emformer_transducer_stateless2/stream.py
- sherpa/bin/conv_emformer_transducer_stateless2/streaming_server.py
- sherpa/bin/lstm_transducer_stateless/beam_search.py
- sherpa/bin/lstm_transducer_stateless/stream.py
- sherpa/bin/lstm_transducer_stateless/streaming_server.py
- sherpa/bin/pruned_stateless_emformer_rnnt2/beam_search.py
- sherpa/bin/pruned_stateless_emformer_rnnt2/stream.py
- sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_client.py
- sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_server.py
- sherpa/bin/streaming_pruned_transducer_statelessX/beam_search.py
- sherpa/bin/streaming_pruned_transducer_statelessX/stream.py
- sherpa/bin/streaming_pruned_transducer_statelessX/streaming_server.py
- sherpa/csrc/hypothesis.h
- sherpa/csrc/online_asr.cc
- sherpa/csrc/rnnt_beam_search.cc
- sherpa/csrc/rnnt_beam_search.h
- sherpa/python/csrc/hypothesis.cc
- sherpa/python/csrc/rnnt_beam_search.cc
- sherpa/python/sherpa/__init__.py
- sherpa/python/sherpa/decode.py
- sherpa/python/sherpa/timestamp.py
- sherpa/python/sherpa/utils.py
- sherpa/python/test/CMakeLists.txt
- sherpa/python/test/test_timestamp.py
- sherpa/python/test/test_utils.py
Copy from : https://github.com/k2-fsa/sherpa/pull/119
> Streaming asr time stamp

- sherpa/bin/conv_emformer_transducer_stateless2/streaming_server.py
- sherpa/bin/lstm_transducer_stateless/streaming_server.py
- sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_server.py
- sherpa/bin/pruned_transducer_statelessX/offline_server.py
- sherpa/bin/streaming_pruned_transducer_statelessX/streaming_server.py
To catch the following exception on the server side:
```
2022-10-12 13:53:28,006 ERROR [server.py:234] connection handler failed
Traceback (most recent call last):
File "/ceph-fj/fangjun/software/py38/lib/python3.8/site-packages/websockets/legacy/server.py", line 232, in handler
await self.ws_handler(self)
File "./sherpa/bin/conv_emformer_transducer_stateless2/streaming_server.py", line 427, in handle_connection
await self.handle_connection_impl(socket)
File "./sherpa/bin/conv_emformer_transducer_stateless2/streaming_server.py", line 527, in handle_connection_impl
await socket.send(json.dumps(message))
File "/ceph-fj/fangjun/software/py38/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 620, in send
await self.ensure_open()
File …
```
> Catch websocket connection closed exception

- docs/source/conf.py
- docs/source/index.rst
- docs/source/onnx/index.rst
We support using [onnx](https://github.com/onnx/onnx) with [onnxruntime](https://github.com/microsoft/onnxruntime) to replace PyTorch for neural network computation. The code is put in a separate repository [sherpa-onnx](https://github.com/k2-fsa/sherpa-onnx).
[sherpa-onnx](https://github.com/k2-fsa/sherpa-onnx) is self-contained and everything can be compiled from source.
> Add doc for sherpa-onnx

- sherpa/csrc/CMakeLists.txt
- sherpa/csrc/ctc_conformer_model.cc
- sherpa/csrc/ctc_conformer_model.h
- sherpa/csrc/ctc_model.h
- sherpa/csrc/rnnt_model.h
Here are the TODO lists. Help from the community is appreciated.
@pkufool  please have a look which part(s) you are interested in.
- log_softmax_out: a 3-D tensor of shape (N, T, C)
- log_softmax_out_lens, a 1-D tensor of shape (N,)
- FsaClassPtr, can be either a CtcTopo or an HLG
and it returns `std::vector<std::vector<int32_t>>`
- https://github.com/k2-fsa/k2/blob/v2.0-pre/k2/torch/bin/ctc_decode.cu
- https://github.com/k2-fsa/k2/blob/v2.0-pre/k2/torch/bin/hlg_decode.cu
- https://github.com/k2-fsa/k2/pull/872
We can use https://github.com/wenet-e2e/wenet/releases/download/v2.0.1/chs.tar.gz and https://github.com/wenet-e2e/wenet/releases/download/v2.0.1/en.tar.gz for testing.
I suggest that we also add scripts to show how to build an HLG graph for models from wenet. We can put the …
> Add CTC models

- sherpa/bin/pruned_stateless_emformer_rnnt2/beam_search.py
- sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_server.py
- sherpa/csrc/online_asr.cc
- sherpa/csrc/rnnt_emformer_model.cc
- sherpa/csrc/rnnt_emformer_model.h
- sherpa/python/csrc/rnnt_emformer_model.cc
After merging this PR, all transducer models, streaming + non-streaming, from icefall are supported in sherpa (C++ & Python).
> Support using Emformer model for online_websocket_server

- triton/README.md
- triton/model_repo_offline_fast_beam/conformer_transducer
- triton/model_repo_offline_fast_beam/decoder
- triton/model_repo_offline_fast_beam/encoder
- triton/model_repo_offline_fast_beam/fast_beam_search/1/model.py
- triton/model_repo_offline_fast_beam/fast_beam_search/config.pbtxt
- triton/model_repo_offline_fast_beam/feature_extractor
- triton/model_repo_offline_fast_beam/joiner
- triton/model_repo_streaming_fast_beam/conformer_transducer
- triton/model_repo_streaming_fast_beam/decoder
- triton/model_repo_streaming_fast_beam/encoder
- triton/model_repo_streaming_fast_beam/fast_beam_search/1/model.py
- triton/model_repo_streaming_fast_beam/fast_beam_search/config.pbtxt
- triton/model_repo_streaming_fast_beam/feature_extractor
- triton/model_repo_streaming_fast_beam/joiner
- triton/scripts/start_offline_server_fast_beam.sh
- triton/scripts/start_streaming_server_fast_beam.sh
This PR adds fast beam search decoding for offline and streaming ASR triton server.
Currently, triton support table 
|  Mode	     | Protobuf	|  Precision|  Decoding Method	    |     Model  	|  Support |
|------------|----------|-----------|-----------------------|---------------|----------|
| Streaming	 |  Onnx	|    FP32	|   Greedy Search	    |  Conformer-T	|   Yes    |
|            |          |           |  Fast Beam Search     |  Conformer-T	|   Yes    |
| Offline	 |  Onnx	|    FP32	|   Greedy Search	    |  Conformer-T	|   Yes    |
| Streaming	 |  Onnx	|    FP16	|   Greedy Search	    |  Conformer-T	|   Yes    |
| Offline	 |  Onnx	|    FP16	|   Greedy Search	    |  Conformer-T	|   Yes    |
|            |          |           |  Fast Beam Search     |  Conformer-T	|   Yes    |
| Offline …
> [Triton] add fast beam search support

- sherpa/cpp_api/online-stream.h
- sherpa/cpp_api/websocket/online-websocket-client.cc
- sherpa/cpp_api/websocket/online-websocket-server-impl.cc
- sherpa/cpp_api/websocket/online-websocket-server-impl.h
- sherpa/cpp_api/websocket/online-websocket-server.cc
This PR is helpful when you have a very long audio file to send.
It can split the audio file into chunks to avoid "payload to big" error.
Also, when a client disconnects, the server stops decoding the samples that it has already received from this disconnected client.
> Send audio samples in chunks for online websocket client

- sherpa/cpp_api/websocket/online-websocket-server-impl.cc
@ngoel17 
Please check this PR. We set `is_final` at the end of decoding an utterance.
> Set is_final for online websocket server

- sherpa/cpp_api/bin/CMakeLists.txt
- sherpa/cpp_api/websocket/CMakeLists.txt
It throws the following error inside a colab notebook:
```
sherpa-offline: error while loading shared libraries: libsherpa_cpp_api.so: cannot open shared object file: No such file or directory
```
```
readelf -d /usr/local/bin/sherpa-offline
```
It prints:
```
Dynamic section at offset 0x228f0 contains 37 entries:
Tag        Type                         Name/Value
0x0000000000000001 (NEEDED)             Shared library: [libsherpa_cpp_api.so]
0x0000000000000001 (NEEDED)             Shared library: [libsherpa_core.so]
0x0000000000000001 (NEEDED)             Shared library: [libtorch_cpu.so]
0x0000000000000001 (NEEDED)             Shared library: [libc10.so]
0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
0x0000000000000001 (NEEDED)             Shared library: …
```
> Fix building for colab

- CMakeLists.txt
If a computer has mkl installed in default location (/opt/intel/.../mkl) and this location is not in library search path, the build process will be failed due to pytorch cmake config.
This will prevent cmake from searching for system MKL since it is installed alongside with pytorch already
> Prevent cmake from trying to link with system MKL

- sherpa/csrc/online-conformer-transducer-model.cc
- sherpa/csrc/online-conv-emformer-transducer-model.cc
- sherpa/csrc/online-emformer-transducer-model.cc
- sherpa/csrc/online-lstm-transducer-model.cc
- sherpa/csrc/online-zipformer-transducer-model.cc
- sherpa/csrc/rnnt_conformer_model.cc
- sherpa/csrc/rnnt_conv_emformer_model.cc
- sherpa/csrc/rnnt_emformer_model.cc
- sherpa/csrc/rnnt_lstm_model.cc
- sherpa/python/csrc/rnnt_beam_search.cc
- sherpa/python/csrc/rnnt_conformer_model.cc
- sherpa/python/csrc/rnnt_conv_emformer_model.cc
- sherpa/python/csrc/rnnt_emformer_model.cc
- sherpa/python/csrc/rnnt_lstm_model.cc
This fix is relevant to #290 . Basically it replaced a lot of `return {*}` with `return std::make_tuple()` for building.
These changes made building successful under environment: 
* torch 1.9.0, cuda 10.2, gcc 5.4.0
* k2 1.23.4.dev20230130+cuda10.2.torch1.9.0
> fix a few scripts for building (issue #290)

- docs/source/onnx/pretrained_models/offline-transducer/code-zipformer/sherpa-onnx-zipformer-en-2023-04-01-int8.txt
- docs/source/onnx/pretrained_models/offline-transducer/code-zipformer/sherpa-onnx-zipformer-en-2023-04-01.txt
- docs/source/onnx/pretrained_models/offline-transducer/zipformer-transducer-models.rst
Update doc to add our best-performing non-streaming zipformer model trained on librispeech + gigaspeech dataset to sherpa-onnx.
> add a new zipformer for sherpa-onnx

- sherpa/bin/streaming_client.py
- sherpa/bin/streaming_server.py
- sherpa/cpp_api/online-recognizer.cc
- sherpa/cpp_api/online-recognizer.h
- sherpa/csrc/online-zipformer-transducer-model.cc
- sherpa/csrc/online-zipformer-transducer-model.h
- sherpa/python/csrc/online-recognizer.cc
- sherpa/python/csrc/online-stream.cc
Closes #356
Closes #357
Closes #320 
Closes #254 
Closes #252 
----
I will refactor the Python websocket server to keep only one `streaming_server.py`, which supports all kinds of
streaming transducer models from icefall.
---
Requires https://github.com/k2-fsa/icefall/pull/1005
> Add streaming websocket server in Python

- docs/source/ncnn/install/riscv64-embedded-linux.rst
We should use `sherpa-ncnn` to decode wave files, not `sherpa-ncnn-alsa`.
> Fix riscv64 docs

- sherpa/csrc/context-graph.cc
- sherpa/csrc/context-graph.h
- sherpa/csrc/test-context-graph.cc
Fix an issue about the failure arc score (the canceling score), I remove the local_node_score which turns out to be an over design and leads to this issue.
I also do some optimization by calculating the output score while compiling the graph.
> Fix context graph

- docs/source/cpp/pretrained_models/online_transducer.rst
The current document for using `icefall-asr-librispeech-streaming-zipformer-2023-05-17` lacks downloading `LG.pt`.
This pull request fixes that.
> Fix a document for icefall-asr-librispeech-streaming-zipformer-2023-05-17

- CMakeLists.txt
- cmake/cmake_extension.py
I was tried building sherpa from source with torch 2.1 but failed with the following error:
```
#error C++17 or later compatible compiler is required to use PyTorch
```
Fixing changing the cpp version in the cmkae file did the trick
> Update cmake to cpp 17

- triton/whisper/requirements.txt
Updates happened that prevent this from working without error so versions must be pinned.
> Fix errors and warnings whisper triton requirements.txt

- .github/workflows/build-doc.yml
- docs/source/onnx/index.rst
- docs/source/onnx/speaker-identification/index.rst
You can find pre-built Android APKs for speaker identification at
https://k2-fsa.github.io/sherpa/onnx/speaker-identification/apk.html
A screenshot is given below:
> Add Android APKs for speaker identification.

- docs/source/onnx/kws/pretrained_models/index.rst
I add github links as an option, I will keep modelscope links as it is. For now in China mainland, we usually have weak connection to github and huggingface, the ModelScope is indeed the most suitable place to hold models for Chinese users.  I think we should care about not only the users who ask questions, but also the users (I think they are more) who don't, host models on ModelScope will benetfit a lot of Chinese users, anyway, that is my opinion.
> Add github model links for keyword-spotting

- sherpa/cpp_api/online-recognizer.cc
- sherpa/cpp_api/online-stream.h
- sherpa/csrc/online-stream.cc
- sherpa/csrc/test-online-stream.cc
By setting --normalize-samples=false, you can invoke the model trained with Kaldi-style features.
Note: sherpa-offline supports setting this option from the command line, while sherpa-online does not support it. This PR is to enable command line setting support for sherpa-online.
Note 2: There are no changes related to pybind, server/client, triton (maybe) submitted here. If you think that 'Replace FbankOptions with FeatureConfig' is worth it (for this requirement or in the future), I am willing to make the necessary changes.
> Replace FbankOptions with FeatureConfig to support 'normalize_samples' option

- sherpa/cpp_api/feature-config.cc
Add two command line feature options, so that it reads "--snip-edges=true --high-freq=0", along with the already supported options "--normalize-samples=false --dither=1", to ensure that the extracted features are consistent with the default kaldi fbank configuration.
> Add command line feature options

- sherpa/csrc/online-lstm-transducer-model.cc
- sherpa/csrc/online-zipformer-transducer-model.cc
- sherpa/csrc/online-zipformer2-transducer-model.cc
When --context-size is 1, there is no conv module at all.
It fixes the following error
```
[I] /xxxx/sherpa/cpp_api/bin/online-recognizer.cc:143:int32_t main(int32_t, char**) 2024-04-08 14:07:07.958 decoding method: greedy_search
terminate called after throwing an instance of 'torch::jit::ObjectAttributeError'
what():  __torch__.torch.nn.modules.linear.Identity (of Python compilation unit at: 0x556bd40) does not have a field with name 'weight'
```
> Support --context-size=1

- .github/workflows/build-doc.yml
- docs/source/onnx/android/build-sherpa-onnx.rst
- docs/source/onnx/audio-tagging/android.rst
- docs/source/onnx/audio-tagging/index.rst
Prebuilt android APKs for audio tagging are available at
https://k2-fsa.github.io/sherpa/onnx/audio-tagging/apk.html
> Doc: Add Android APKs for audio tagging

- docs/source/onnx/install/aarch64-embedded-linux.rst
paths are mis-ordered respect to args
> fix doc error in example command

- sherpa/csrc/offline-ctc-one-best-decoder.cc
原来的第68行
```cpp
if (t != 0 && !p->tokens.empty() && token == p->tokens.back())
```
没有判断输出字符是否被blank分隔，导致相邻的重复字符会被合并为一个。
添加了变量`bool last_token_is_blank`作为标志位来判断是否被blank分隔，修复了这个问题。
> Fixed the problem that the duplicated characters would be merged as one.

- .pre-commit-config.yaml
- triton/whisper/model_repo_whisper_trtllm/infer_bls/1/model.py
- triton/whisper/model_repo_whisper_trtllm/whisper/1/model.py
Thank you for sharing this impressive project.
I have modified whisper tritonserver to support batch inference.(#650) 
Additionally, due to an issue with isort (https://github.com/PyCQA/isort/issues/2228),  I updated the version of isort in pre-commit to `5.13.2`.
I confirmed that the results are consistent whether batch inference is used or not.
> Add whisper tritonserver batch inference (#650)
