README.md
sherpa/bin/decode_manifest.py

I just added a colab notebook
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1JX5Ph2onYm1ZjNP_94eGqZ-DIRMLlIca?usp=sharing)
showing how to use `sherpa`:
- how to install sherpa
- how to start the server
- how to start the client
- how to decode test-clean

Add Colab notebook link.

---

sherpa/bin/decode_manifest.py
sherpa/bin/offline_client.py
sherpa/bin/offline_server.py
sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_client.py
sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_server.py

Support to limit the number of active connections.

---

sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_server.py

disabling the gradient calculations on running the model

Adding no_grad to streaming_server

---

.github/workflows/run-streaming-conformer-test.yaml
README.md
sherpa/bin/streaming_conformer_rnnt/decode.py
sherpa/bin/streaming_conformer_rnnt/streaming_server.py
sherpa/csrc/rnnt_beam_search.cc
sherpa/python/csrc/rnnt_model.cc

Fixed  https://github.com/k2-fsa/sherpa/pull/17#issuecomment-1152832062

Fix streaming conformer

---

README.md
docs/source/conf.py
docs/source/index.rst
docs/source/offline_asr/conformer/aishell.rst
docs/source/offline_asr/conformer/code/client-results-librispeech.txt
docs/source/offline_asr/conformer/code/client-results.txt
docs/source/offline_asr/conformer/code/offline-client-help.txt
docs/source/offline_asr/conformer/code/offline-server-help.txt
docs/source/offline_asr/conformer/code/start-the-client-librispeech.sh
docs/source/offline_asr/conformer/code/start-the-client.sh
docs/source/offline_asr/conformer/code/start-the-server-librispeech.sh
docs/source/offline_asr/conformer/code/start-the-server.sh
docs/source/offline_asr/conformer/index.rst
docs/source/offline_asr/conformer/librispeech.rst
docs/source/offline_asr/index.rst
docs/source/streaming_asr/emformer/index.rst
docs/source/streaming_asr/emformer/server.rst
docs/source/streaming_asr/index.rst

A preview is available at https://csukuangfj.github.io/sherpa/index.html

Update doc to include offline ASR.

---

README.md
sherpa/bin/web/README.md
sherpa/bin/web/js/offline_record.js
sherpa/bin/web/js/streaming_record.js
sherpa/bin/web/nav-partial.html
sherpa/bin/web/offline_record.html
sherpa/bin/web/streaming_record.html

This PR is to add offline ASR for web demo.

[Ready to merge] Add offline ASR for web demo

---

sherpa/bin/conformer_rnnt/decode.py
sherpa/bin/conformer_rnnt/offline_asr.py
sherpa/bin/conformer_rnnt/offline_server.py

Fixes #57 
```bash
(1) Pre-trained model with the LibriSpeech dataset
sudo apt-get install git-lfs
git lfs install
git clone https://huggingface.co/csukuangfj/icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13
nn_model_filename=./icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/exp/cpu_jit-torch-1.6.0.pt
bpe_model=./icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/data/lang_bpe_500/bpe.model
wav1=./icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/test_wavs/1089-134686-0001.wav
wav2=./icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/test_wavs/1221-135766-0001.wav
wav3=./icefall-asr-librispeech-pruned-transducer-stateless3-2022-05-13/test_wavs/1221-135766-0002.wav
sherpa/bin/conformer_rnnt/offline_asr.py \ …
```

Add standalone offline ASR script.

---

docs/source/conf.py
docs/source/streaming_asr/conv_emformer/client.rst
docs/source/streaming_asr/conv_emformer/index.rst
docs/source/streaming_asr/conv_emformer/server.rst
docs/source/streaming_asr/emformer/client.rst
docs/source/streaming_asr/index.rst

This PR adds documents for ConvEmformer.

add doc of conv_emformer

---

sherpa/bin/conv_emformer_transducer_stateless2/streaming_server.py
sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_client.py
sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_server.py
sherpa/bin/pruned_transducer_statelessX/offline_asr.py
sherpa/bin/pruned_transducer_statelessX/offline_client.py
sherpa/bin/pruned_transducer_statelessX/offline_server.py
sherpa/bin/streaming_pruned_transducer_statelessX/streaming_server.py

something I have noticed. 
I can implemennt the check for other servers as well, if this is something welcomed.

make sure at least one of the bpe-model or token-model is defined

---

README.md
docs/source/huggingface/index.rst

See https://www.youtube.com/watch?v=ElN3r9dkKE4
Preview:

Update doc to add a link to Nadira Povey's YouTube channel

---

.github/workflows/run-cpp-test.yaml
CMakeLists.txt
sherpa/csrc/CMakeLists.txt
sherpa/csrc/log.cc
sherpa/csrc/log.h
sherpa/csrc/test_log.cc

The implementation is copied & modified from
https://github.com/k2-fsa/k2/blob/master/k2/csrc/log.h

Add SHERPA_LOG() and SHERPA_CHECK().

---

CMakeLists.txt
scripts/conda-cpu/sherpa/meta.yaml

Add C++ frontend. Support compiling sherpa as a standalone binary.
See https://k2-fsa.github.io/sherpa/cpp/installation/index.html for installation.
See https://k2-fsa.github.io/sherpa/cpp/offline_asr/index.html for usage.
Note: It supports `conda install` on Linux/macOS/Windows.

Release v0.7

---

CMakeLists.txt
scripts/conda-cpu/sherpa/meta.yaml

Release v0.8

---

.github/workflows/build-conda-cpu.yaml
.github/workflows/build-doc.yml
.github/workflows/run-cpp-test.yaml
.github/workflows/run-streaming-conformer-test.yaml
.github/workflows/run-streaming-conv-emformer-test.yaml
.github/workflows/run-streaming-test-windows-cpu.yaml
.github/workflows/run-streaming-test-windows-cuda.yaml
.github/workflows/run-streaming-test-with-long-waves.yaml
.github/workflows/run-streaming-test.yaml
.github/workflows/run-test-aishell.yaml
.github/workflows/run-test-windows-cpu.yaml
.github/workflows/run-test-windows-cuda.yaml
.github/workflows/run-test.yaml
.github/workflows/run-wenetspeech-streaming-conformer-rnnt-test.yaml
.github/workflows/test-conda-install.yaml
CMakeLists.txt
cmake/cmake_extension.py
docs/source/cpp/installation/conda-linux.rst
docs/source/cpp/installation/conda-windows.rst
docs/source/cpp/installation/from-source.rst
requirements.txt
scripts/conda-cpu/sherpa/meta.yaml
setup.py

We are compiling it from source.

Remove kaldi_native_io from python deps

---

sherpa/bin/lstm_transducer_stateless/beam_search.py
sherpa/bin/lstm_transducer_stateless/streaming_server.py
sherpa/bin/web/js/streaming_record.js

https://user-images.githubusercontent.com/5284924/190886305-698a8364-ea3d-45a7-9d2d-eb351e713960.mp4
```bash
nn_model_filename=./icefall-asr-librispeech-conv-emformer-transducer-stateless2-2022-07-05/exp/cpu-jit-epoch-30-avg-10-torch-1.10.0.pt
bpe_model_filename=./icefall-asr-librispeech-conv-emformer-transducer-stateless2-2022-07-05/data/lang_bpe_500/bpe.model
./sherpa/bin/conv_emformer_transducer_stateless2/streaming_server.py \
--endpoint.rule1.must-contain-nonsilence=false \
--endpoint.rule1.min-trailing-silence=5.0 \
--endpoint.rule2.min-trailing-silence=2.0 \
--endpoint.rule3.min-utterance-length=40.0 \
--port 6006 \
--decoding-method fast_beam_search \
--max-batch-size 50 \
--max-wait-ms 5 \
--nn-pool-size 1 \
--max-active-connections 10 \
--nn-model-filename $nn_model_filename \ …
```

Fix displaying results in the web client

---

CMakeLists.txt
scripts/conda-cpu/sherpa/meta.yaml

Release v0.9

---

docs/source/python/streaming_asr/conformer/conformer_rnnt_for_Chinese/server.rst
docs/source/python/streaming_asr/conformer/conformer_rnnt_for_English/server.rst
docs/source/python/streaming_asr/conv_emformer/server.rst
docs/source/python/streaming_asr/emformer/server.rst
docs/source/python/streaming_asr/endpointing.rst
docs/source/python/streaming_asr/lstm/chinese/server.rst
docs/source/python/streaming_asr/lstm/english/server.rst
sherpa/bin/web/js/streaming_record.js

See https://k2-fsa.github.io/sherpa/python/streaming_asr/endpointing.html for details

Add endpointing YouTube video demo.

---

docs/source/conf.py
docs/source/index.rst
docs/source/ncnn/index.rst

You can find a demo at
https://www.youtube.com/watch?v=m6ynSxycpX0
It shows you how to install sherpa-ncnn on macOS and how to use it for real-time speech recognition with a microphone.

add doc for sherpa-ncnn

---

CMakeLists.txt
cmake/kaldi_native_io.cmake
cmake/portaudio.cmake
docs/source/cpp/online_asr/index.rst
docs/source/index.rst
sherpa/cpp_api/CMakeLists.txt
sherpa/cpp_api/test_online_recognizer.cc
sherpa/cpp_api/test_online_recognizer_microphone.cc
sherpa/csrc/log.h
sherpa/csrc/online_stream.cc

https://user-images.githubusercontent.com/5284924/191658907-3748a24d-1c99-47b3-84d3-08defdf3f729.mp4

Add a demo about using C++ API of sherpa for real-time speech recognition from a microphone

---

sherpa/bin/lstm_transducer_stateless/beam_search.py
sherpa/bin/lstm_transducer_stateless/offline_asr.py
sherpa/csrc/rnnt_lstm_model.cc
sherpa/csrc/rnnt_lstm_model.h
sherpa/python/csrc/rnnt_lstm_model.cc

so that users can provide a model and wave files for recognition without the need to start a server and a client.
```bash
git lfs install
git clone https://huggingface.co/csukuangfj/icefall-asr-librispeech-lstm-transducer-stateless2-2022-09-03
nn_encoder_filename=./icefall-asr-librispeech-lstm-transducer-stateless2-2022-09-03/exp/encoder_jit_trace-iter-468000-avg-16.pt
nn_decoder_filename=./icefall-asr-librispeech-lstm-transducer-stateless2-2022-09-03/exp/decoder_jit_trace-iter-468000-avg-16.pt
nn_joiner_filename=./icefall-asr-librispeech-lstm-transducer-stateless2-2022-09-03/exp/joiner_jit_trace-iter-468000-avg-16.pt
bpe_model_filename=./icefall-asr-librispeech-lstm-transducer-stateless2-2022-09-03/data/lang_bpe_500/bpe.model
./sherpa/bin/lstm_transducer_stateless/offline_asr.py \ …
```

Add offline_asr for lstm-transducer

---

sherpa/bin/pruned_transducer_statelessX/beam_search.py
sherpa/bin/pruned_transducer_statelessX/offline_server.py

Hi, please have a look @csukuangfj

Add fp16 for pruned_transducer_statelessX

---

sherpa/csrc/rnnt_lstm_model.cc
sherpa/csrc/rnnt_lstm_model.h
sherpa/python/csrc/rnnt_lstm_model.cc

So that we can wrap it to `OnlineStream`.
https://github.com/k2-fsa/sherpa/blob/c235538f36bcf59023caecfe594fa9ee2c6177cd/sherpa/cpp_api/online_stream.h#L32

Refactor the LSTM model to use an IValue for state.

---

sherpa/bin/conv_emformer_transducer_stateless2/streaming_server.py
sherpa/csrc/rnnt_conformer_model.cc
sherpa/csrc/rnnt_conformer_model.h
sherpa/csrc/rnnt_conv_emformer_model.cc
sherpa/csrc/rnnt_conv_emformer_model.h
sherpa/csrc/rnnt_lstm_model.cc
sherpa/csrc/rnnt_lstm_model.h
sherpa/csrc/rnnt_model.h
sherpa/python/csrc/rnnt_conformer_model.cc
sherpa/python/csrc/rnnt_conv_emformer_model.cc
sherpa/python/csrc/rnnt_lstm_model.cc

The goal is to use `RnntModel` in the C++ API.

Refactor rnnt model for streaming c++ api

---

sherpa/bin/conv_emformer_transducer_stateless2/streaming_server.py
sherpa/bin/lstm_transducer_stateless/beam_search.py
sherpa/bin/lstm_transducer_stateless/streaming_server.py
sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_server.py
sherpa/bin/pruned_transducer_statelessX/offline_server.py
sherpa/bin/streaming_pruned_transducer_statelessX/streaming_server.py
sherpa/bin/web/js/offline_record.js
sherpa/bin/web/js/streaming_record.js
sherpa/bin/web/js/upload.js
sherpa/python/sherpa/__init__.py
sherpa/python/sherpa/http_server.py

Serve http and websocket on the same port

---

.github/scripts/test-websocket-rtf-wer.sh
.github/workflows/test-websocket-rtf-wer.yaml

Here are the results:
---
Machine configuration of GitHub actions:

Compute RTF of websocket in GitHub actions

---

sherpa/cpp_api/online_stream.h
sherpa/csrc/online_asr.cc
sherpa/csrc/online_stream.cc
sherpa/csrc/rnnt_conv_emformer_model.cc
sherpa/csrc/rnnt_conv_emformer_model.h
sherpa/csrc/rnnt_model.h

Refactor OnlineStream

---

.github/scripts/test-websocket-rtf-wer.sh
.github/workflows/test-websocket-rtf-wer.yaml
sherpa/bin/conv_emformer_transducer_stateless2/streaming_server.py
sherpa/bin/lstm_transducer_stateless/streaming_server.py
sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_client.py
sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_server.py
sherpa/bin/pruned_transducer_statelessX/decode_manifest.py
sherpa/bin/pruned_transducer_statelessX/offline_client.py
sherpa/bin/pruned_transducer_statelessX/offline_server.py
sherpa/bin/streaming_pruned_transducer_statelessX/streaming_server.py
sherpa/bin/web/js/offline_record.js
sherpa/bin/web/js/streaming_record.js
sherpa/bin/web/js/upload.js
sherpa/cpp_api/websocket/offline_websocket_client.cc
sherpa/cpp_api/websocket/offline_websocket_server_impl.cc
sherpa/cpp_api/websocket/offline_websocket_server_impl.h

Compute RTF on Ubuntu for websocket

---

sherpa/bin/conv_emformer_transducer_stateless2/streaming_server.py
sherpa/bin/pruned_transducer_statelessX/offline_server.py
sherpa/bin/streaming_pruned_transducer_statelessX/beam_search.py
sherpa/bin/streaming_pruned_transducer_statelessX/streaming_server.py
sherpa/csrc/offline_asr.cc
sherpa/csrc/rnnt_conformer_model.cc
sherpa/csrc/rnnt_conformer_model.h
sherpa/csrc/rnnt_model.h
sherpa/python/csrc/rnnt_conformer_model.cc

This is the first one among a series of refactors to reduce the duplication on the python side.

Refactor streaming conformer

---

sherpa/cpp_api/websocket/offline-websocket-client.cc
sherpa/cpp_api/websocket/online-websocket-client.cc

Support num_messages_per_seconds in floating point

---

sherpa/cpp_api/websocket/online-websocket-client.cc

Please review the code first. Somehow it's not closing the connection after the transcription is complete.

simulate streaming by introducing delay between packets

---

docs/source/triton/client/index.rst
docs/source/triton/perf/code/offline_perf.txt
docs/source/triton/perf/index.rst
triton/client/decode_manifest_offline.py
triton/model_repo_offline/scorer/1/model.py
triton/model_repo_offline/scorer/1/search.py
triton/model_repo_offline/scorer/config.pbtxt.template

- Add missed log.txt for triton docs #208 
- Add a decode manifest python file
- Reconstruct scorer file: extract greedy search function

Decode manifest

---

.github/scripts/run-online-transducer.sh
sherpa/cpp_api/CMakeLists.txt
sherpa/cpp_api/bin/online-recognizer-microphone.cc
sherpa/cpp_api/endpoint.cc
sherpa/cpp_api/endpoint.h
sherpa/cpp_api/online-recognizer.cc
sherpa/cpp_api/online-recognizer.h
sherpa/cpp_api/online-stream.h
sherpa/csrc/CMakeLists.txt
sherpa/csrc/online-stream.cc
sherpa/csrc/online-transducer-fast-beam-search-decoder.cc

Add endpoint as https://github.com/k2-fsa/sherpa/issues/229

add endpoint

---

.github/scripts/run-offline-ctc.sh
docs/source/cpp/pretrained_models/index.rst
docs/source/cpp/pretrained_models/offline_ctc.rst

See https://github.com/k2-fsa/icefall/pull/396
Thanks @AmirHussein96

Add Arabic pretrained models

---

.github/scripts/run-online-transducer.sh
.github/workflows/run-cpp-test.yaml
.github/workflows/run-cpp-websocket-test.yaml
sherpa/cpp_api/bin/online-recognizer.cc
sherpa/cpp_api/endpoint.cc
sherpa/cpp_api/endpoint.h
sherpa/cpp_api/online-recognizer.cc

Reduce ci test time

---

.github/scripts/run-python-test.sh
.github/workflows/run-cpp-test.yaml
.github/workflows/run-python-test.yaml
.gitignore
sherpa/cpp_api/fast-beam-search-config.cc
sherpa/cpp_api/fast-beam-search-config.h
sherpa/cpp_api/feature-config.cc
sherpa/cpp_api/feature-config.h
sherpa/cpp_api/offline-recognizer.cc
sherpa/cpp_api/offline-recognizer.h
sherpa/python/csrc/CMakeLists.txt
sherpa/python/csrc/fast-beam-search-config.cc
sherpa/python/csrc/fast-beam-search-config.h
sherpa/python/csrc/feature-config.cc
sherpa/python/csrc/feature-config.h
sherpa/python/csrc/offline-ctc-model.cc
sherpa/python/csrc/offline-ctc-model.h
sherpa/python/csrc/offline-recognizer.cc
sherpa/python/csrc/offline-recognizer.h
sherpa/python/csrc/offline-stream.cc
sherpa/python/csrc/offline-stream.h
sherpa/python/csrc/sherpa.cc
sherpa/python/sherpa/__init__.py
sherpa/python/test/CMakeLists.txt
sherpa/python/test/test_fast_beam_search_config.py
sherpa/python/test/test_feature_config.py
sherpa/python/test/test_offline_ctc_decoder_config.py
sherpa/python/test/test_offline_recognizer.py
sherpa/python/test/test_offline_recognizer_config.py

Will add doc and tests in separate PRs.

Add new Python API for offline recognizer.

---

docs/source/cpp/pretrained_models/index.rst

Add colab link to sherpa/docs/source/cpp/pretrained_models/index.rst

Add colab link to sherpa/docs/source/cpp/pretrained_models/index.rst

---

.github/workflows/run-streaming-conv-emformer-test.yaml
sherpa/bin/conv_emformer_transducer_stateless2/beam_search.py
sherpa/bin/conv_emformer_transducer_stateless2/streaming_server.py
sherpa/bin/streaming_pruned_transducer_statelessX/streaming_server.py

So that we can use the model from
https://huggingface.co/ptrnull/icefall-asr-conv-emformer-transducer-stateless2-zh

Support passing token.txt to conv-emformer streaming server

---

.github/scripts/run-offline-ctc.sh
.github/scripts/run-offline-transducer.sh
.github/workflows/run-cpp-test.yaml
docs/source/cpp/pretrained_models/offline_ctc.rst
docs/source/cpp/pretrained_models/offline_transducer.rst
docs/source/ncnn/index.rst

- Fixes https://github.com/k2-fsa/sherpa-ncnn/issues/34
- Add pre-trained models from 
- https://github.com/k2-fsa/icefall/pull/13 
- https://github.com/k2-fsa/icefall/pull/696
- https://github.com/k2-fsa/icefall/pull/751

Update doc to include newly added CTC models

---

docs/source/cpp/pretrained_models/offline_ctc.rst
docs/source/ncnn/android/index.rst
docs/source/ncnn/index.rst
docs/source/ncnn/install/aarch64-embedded-linux.rst
docs/source/ncnn/install/arm-embedded-linux.rst
docs/source/ncnn/install/index.rst
docs/source/ncnn/install/linux.rst
docs/source/ncnn/install/macos.rst
docs/source/ncnn/install/windows.rst
docs/source/ncnn/pretrained_models/index.rst

Will add doc about pre-trained models and how to build an Android app in separate PRs.

Add doc for cross-compiling sherpa-ncnn.

---

sherpa/bin/pruned_transducer_statelessX/offline_server.py

Correcting initialize RnntConformerModel when using CUDA

---

sherpa/cpp_api/bin/offline-recognizer.cc

Fix comment error, please see the commit for the details.

Fix comment error

---

triton/client/decode_manifest_triton.py

For streaming ASR, we care about concurrent more comparing with throughput. This PR adds chunk latency metric and simulate streaming mode to better benchmark streaming triton asr.

Add simulate streaming mode for triton client

---

.github/scripts/run-online-transducer.sh
.github/workflows/run-python-test.yaml
.github/workflows/run-streaming-conformer-test.yaml
.github/workflows/run-streaming-conv-emformer-test.yaml
.github/workflows/run-streaming-lstm-test.yaml
.github/workflows/run-streaming-test-with-long-waves.yaml
.github/workflows/run-streaming-test.yaml
.github/workflows/run-test-aishell.yaml
.github/workflows/run-test.yaml
.github/workflows/run-wenetspeech-streaming-conformer-rnnt-test.yaml
docs/source/cpp/pretrained_models/online_transducer.rst
docs/source/ncnn/ios/demo-videos.rst
sherpa/python/test/test_online_recognizer.py

The streaming multilingual (Chinese + English) zipformer model is from
https://huggingface.co/pfluo/k2fsa-zipformer-chinese-english-mixed
which is contributed by the community.

Add multilingual (Chinese+English) streaming zipformer

---

triton/scripts/start_offline_server_zipformer.sh
triton/zipformer/model_repo_offline/decoder/config.pbtxt
triton/zipformer/model_repo_offline/encoder/config.pbtxt
triton/zipformer/model_repo_offline/feature_extractor/1/model.py
triton/zipformer/model_repo_offline/feature_extractor/config.pbtxt
triton/zipformer/model_repo_offline/joiner/config.pbtxt
triton/zipformer/model_repo_offline/joiner_decoder_proj/config.pbtxt
triton/zipformer/model_repo_offline/joiner_encoder_proj/config.pbtxt
triton/zipformer/model_repo_offline/scorer/1/model.py
triton/zipformer/model_repo_offline/scorer/1/search.py
triton/zipformer/model_repo_offline/scorer/config.pbtxt
triton/zipformer/model_repo_offline/transducer/config.pbtxt

Hi all,
This PR adds Zipformer Offline with greedy search support in Triton.

[Triton] Add Zipformer Offline support

---

docs/source/ncnn/pretrained_models/lstm-transducer-models.rst
docs/source/ncnn/pretrained_models/small-models.rst

This PR adds docs for a small LSTM transducer model supporting both Chinese and English.

Add docs for lstm small model

---

docs/source/triton/overview.rst
docs/source/triton/trt/index.rst
triton/trt/README.md
triton/trt/model_repo_offline_fast_beam_trt/conformer_transducer/config.pbtxt
triton/trt/model_repo_offline_fast_beam_trt/decoder/config.pbtxt
triton/trt/model_repo_offline_fast_beam_trt/encoder/config.pbtxt
triton/trt/model_repo_offline_fast_beam_trt/fast_beam_search/1/model.py
triton/trt/model_repo_offline_fast_beam_trt/fast_beam_search/config.pbtxt
triton/trt/model_repo_offline_fast_beam_trt/feature_extractor/1/model.py
triton/trt/model_repo_offline_fast_beam_trt/feature_extractor/config.pbtxt
triton/trt/model_repo_offline_fast_beam_trt/joiner/config.pbtxt
triton/trt/tools/build.sh
triton/trt/tools/install.sh

Hi all,
This PR gives how to convert Conformer Offline ONNX model to TRT.
We also show  throughput and latency comparisons of TRT vs ONNX.
Generally, TRT gives avg ~26.5% speed up. See README.md for details. 
We will benchmark the whole pipeline perf improvements later.
Also, we will support Zipformer TRT , streaming models and INT8 in the coming days.
Thanks!!

Support TensorRT FP16 for Conformer Offline encoder model

---

sherpa/bin/offline_transducer_asr.py

Added the number of threads argument and created a separate function that contains the resources' parameters.
The changes are only local to `offline_transucer_asr.py` and will propagate if the overall structure is approved.

Added a "number of threads" argument

---

cmake/asio.cmake
cmake/googletest.cmake
cmake/json.cmake
cmake/kaldi_native_io.cmake
cmake/portaudio.cmake
cmake/pybind11.cmake
cmake/websocketpp.cmake

People from China have difficulty downloading cmake dependencies from github.
This commit adds alternative URLs for downloading deps.

Add alternative URLs for downloading cmake dependencies.

---

CMakeLists.txt
scripts/conda-cpu/sherpa/meta.yaml

- Support pre-trained CTC models from NeMo

Release v1.2

---

sherpa/bin/streaming_pruned_transducer_statelessX/streaming_server.py

Propagated the changes from #323 to streaming stateless transducer.

Added a "number of threads" argument for streaming

---

docs/source/conf.py
docs/source/cpp/pretrained_models/online_transducer.rst
docs/source/ncnn/pretrained_models/zipformer-transucer-models.rst
docs/source/onnx/pretrained_models/online-transducer/zipformer-transducer-models.rst
docs/source/python/installation/from-source.rst
docs/source/python/offline_asr/standalone/transducer.rst
docs/source/python/streaming_asr/index.rst
docs/source/python/streaming_asr/standalone/index.rst
docs/source/python/streaming_asr/standalone/transducer.rst
sherpa/bin/offline_ctc_asr.py
sherpa/bin/offline_transducer_asr.py
sherpa/bin/online_transducer_asr.py
sherpa/python/csrc/offline-stream.cc

See https://k2-fsa.github.io/sherpa/python/streaming_asr/standalone/transducer.html
for usages.

Add standalone Python script for online recognition

---

triton/README.md

\
https://github.com/k2-fsa/sherpa/issues/371#issuecomment-1531199009

add missing git lfs command to docs

---

sherpa/python/sherpa/online_endpoint.py

Fixes #388
The issue in #388 exists only in Python 3.11+, I think.
See also https://github.com/huggingface/datasets/issues/5230

Fix online endpoint for python 3.11

---

sherpa/cpp_api/parse-options.h

Related: https://github.com/csukuangfj/kaldi_native_io/pull/51

Add missing header due to gcc/g++ 13 changes

---

triton/README.md
triton/requirements.txt
triton/scripts/build_wenetspeech_pruned_transducer_stateless5_streaming.sh

fix requirements

---

sherpa/python/sherpa/utils.py

The current code will only append the ids of the last string in the contexts list. This line of code should be moved to the inner for loop instead.

Fix bpe+char bug

---

sherpa/csrc/offline-transducer-greedy-search-decoder.cc
sherpa/csrc/offline-transducer-modified-beam-search-decoder.cc
sherpa/csrc/online-transducer-greedy-search-decoder.cc
sherpa/csrc/online-transducer-modified-beam-search-decoder.cc

See also https://github.com/k2-fsa/icefall/issues/1206 and https://github.com/k2-fsa/icefall/pull/1208

Fix initial tokens for decoding.

---

docs/source/conf.py
docs/source/onnx/install/windows.rst
docs/source/onnx/tts/faq.rst
docs/source/onnx/tts/pretrained_models/index.rst
docs/source/onnx/tts/pretrained_models/vits.rst

- Update FAQs for TTS
- Create a table containing information about all pre-trained TTS models

update doc for tts in sherpa-onnx

---

docs/source/onnx/install/aarch64-embedded-linux.rst
docs/source/onnx/pretrained_models/whisper/index.rst

Describe how to build static libraries and static linked binaries.

Update aarch64 cross-compiling doc for sherpa-onnx.

---

sherpa/bin/offline_ctc_asr.py
sherpa/bin/offline_ctc_server.py
sherpa/bin/offline_transducer_asr.py
sherpa/bin/offline_transducer_server.py
sherpa/bin/online_transducer_asr.py
sherpa/bin/streaming_server.py
sherpa/python/test/test_offline_recognizer.py
sherpa/python/test/test_online_recognizer.py

See also https://github.com/k2-fsa/sherpa-onnx/issues/514
Note that this is a bug-fix.

Use high_freq -400 in computing fbank features.

---

docs/source/onnx/pretrained_models/offline-transducer/code-zipformer/sherpa-onnx-zipformer-cantonese-2024-03-13-int8.txt
docs/source/onnx/pretrained_models/offline-transducer/code-zipformer/sherpa-onnx-zipformer-cantonese-2024-03-13.txt
docs/source/onnx/pretrained_models/offline-transducer/zipformer-transducer-models.rst

It can reduce deletion errors for the test wave.

Doc: Add blank penalty for Cantonese zipformer model

---

docs/source/ncnn/ios/build-sherpa-ncnn-swift.rst
docs/source/onnx/android/build-sherpa-onnx.rst
docs/source/onnx/ios/build-sherpa-onnx-swift.rst

See also
https://github.com/k2-fsa/sherpa-onnx/issues/702

Doc: Describe how to fix iOS build errors.

---

sherpa/csrc/online-zipformer-transducer-model.cc

More fixes to --context-size=1

---

.github/workflows/build-doc.yml
docs/source/index.rst
docs/source/pdf.rst

You can download it from
https://k2-fsa.github.io/sherpa/sherpa.pdf

Provide a single pdf containing all the doc for downloading

---

triton/whisper/Dockerfile.server

fix trt-llm version in `Dockerfile.server` to avoid issue during building step: `tensorrt_llm==0.9.0.dev2024040900`
ref: https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/whisper/requirements.txt

:bug: fix issue on trt-llm dev version

---

triton/whisper/Dockerfile.server

[Triton] [Whisper] update triton whisper docker file

---

triton/whisper/Dockerfile.server
triton/whisper/README.md
triton/whisper/docker-compose.yml
triton/whisper/model_repo_whisper_trtllm/whisper/1/whisper_trtllm.py

Fix #600.
@csukuangfj  Would you mind helping check it? Many thanks.

[Triton] [Whisper] update with latest workflow

---

docs/source/intro.rst
docs/source/onnx/java-api/build-jar.rst
docs/source/onnx/java-api/build-jni-linux.rst
docs/source/onnx/java-api/build-jni-macos.rst
docs/source/onnx/java-api/build-jni-windows.rst
docs/source/onnx/java-api/index.rst

Describe how to download pre-built JNI libs and jar files.

Update java api doc

---

.github/workflows/build-doc.yml
docs/source/onnx/python/install.rst

Please see
- https://k2-fsa.github.io/sherpa/onnx/cpu.html 
- https://k2-fsa.github.io/sherpa/onnx/cpu-cn.html

Add dedicated pages for pre-compiled wheels of sherpa-onnx

---

docs/source/onnx/faqs/index.rst

See also
https://github.com/k2-fsa/sherpa-onnx/pull/925

Update FAQ doc.

---

.github/workflows/build-doc.yml
docs/source/intro.rst
docs/source/onnx/android/build-sherpa-onnx.rst
docs/source/onnx/index.rst
docs/source/onnx/speaker-diarization/android.rst
docs/source/onnx/speaker-diarization/c.rst
docs/source/onnx/speaker-diarization/cpp.rst
docs/source/onnx/speaker-diarization/csharp.rst
docs/source/onnx/speaker-diarization/dart.rst
docs/source/onnx/speaker-diarization/go.rst
docs/source/onnx/speaker-diarization/index.rst
docs/source/onnx/speaker-diarization/java.rst
docs/source/onnx/speaker-diarization/javascript.rst
docs/source/onnx/speaker-diarization/kotlin.rst
docs/source/onnx/speaker-diarization/pascal.rst
docs/source/onnx/speaker-diarization/python.rst
docs/source/onnx/speaker-diarization/swift.rst

Please see https://k2-fsa.github.io/sherpa/onnx/speaker-diarization/

Doc for speaker diarization

---

docs/source/onnx/speaker-diarization/code/pyannote-segmentation-3-0-3dspeaker.int8.txt
docs/source/onnx/speaker-diarization/code/pyannote-segmentation-3-0-3dspeaker.txt
docs/source/onnx/speaker-diarization/code/pyannote-segmentation-3-0-nemo.int8.txt
docs/source/onnx/speaker-diarization/code/pyannote-segmentation-3-0-nemo.txt
docs/source/onnx/speaker-diarization/code/revai-segmentation-3-0-3dspeaker.int8.txt
docs/source/onnx/speaker-diarization/code/revai-segmentation-3-0-3dspeaker.txt
docs/source/onnx/speaker-diarization/code/revai-segmentation-3-0-nemo.int8.txt
docs/source/onnx/speaker-diarization/code/revai-segmentation-3-0-nemo.txt
docs/source/onnx/speaker-diarization/index.rst
docs/source/onnx/speaker-diarization/models.rst

Please see
https://k2-fsa.github.io/sherpa/onnx/speaker-diarization/models.html

Doc for speaker segmentation models

---

docs/source/onnx/tts/wasm/install-emscripten.rst
docs/source/onnx/wasm/install-emscripten.rst

See also https://github.com/k2-fsa/sherpa-onnx/issues/1397

Fix the emsdk version for building WebAssembly.

---

docs/source/onnx/install/linux.rst

See also https://k2-fsa.github.io/sherpa/onnx/install/linux.html

Update doc to include building sherpa-onnx with GPU for Linux arm64.

---

docs/source/onnx/tts/pretrained_models/index.rst
docs/source/onnx/tts/pretrained_models/matcha.rst
docs/source/onnx/tts/pretrained_models/rtf.rst
docs/source/onnx/tts/pretrained_models/vits.rst

Please see
https://k2-fsa.github.io/sherpa/onnx/tts/pretrained_models/rtf.html

Add RTF for TTS models

---

.github/workflows/build-doc.yml
docs/source/onnx/android/prebuilt-apk.rst

The docker image `reitzig/texlive-full:latest` is no longer available.

Fix building doc

---

.github/workflows/export-sense-voice.yml
scripts/sense-voice/export.py
scripts/sense-voice/run.sh

See also
https://www.modelscope.cn/models/iic/SenseVoiceSmall/summary

Export the SenseVoice model to torchscript

---

.github/workflows/export-pyannote.yaml
.gitignore
scripts/pyannote/segmentation/LICENSE
scripts/pyannote/segmentation/README.md
scripts/pyannote/segmentation/export.py
scripts/pyannote/segmentation/vad.py

It can be used for speaker segmentation. Combining with a speaker embedding extractor model, it can be used for speaker diarization.

Export Pyannote models to torchscript

---

python-api-examples/compute-speaker-simiarlity.py
python-api-examples/vad-with-sense-voice.py
sherpa/csrc/CMakeLists.txt
sherpa/csrc/sherpa-compute-speaker-similarity.cc
sherpa/csrc/sherpa-vad.cc
sherpa/csrc/speaker-embedding-extractor-general-impl.h
sherpa/csrc/speaker-embedding-extractor-impl.cc
sherpa/csrc/speaker-embedding-extractor-impl.h
sherpa/csrc/speaker-embedding-extractor-model-meta-data.h
sherpa/csrc/speaker-embedding-extractor-model.cc
sherpa/csrc/speaker-embedding-extractor-model.h
sherpa/csrc/speaker-embedding-extractor.cc
sherpa/csrc/speaker-embedding-extractor.h
sherpa/csrc/voice-activity-detector-silero-vad-impl.h
sherpa/python/csrc/CMakeLists.txt
sherpa/python/csrc/sherpa.cc
sherpa/python/csrc/sherpa.h
sherpa/python/csrc/speaker-embedding-extractor.cc
sherpa/python/csrc/speaker-embedding-extractor.h
sherpa/python/sherpa/__init__.py

Add C++ API for speaker embedding models.

---

docs/source/onnx/index.rst
docs/source/onnx/install/aarch64-embedded-linux.rst
docs/source/onnx/rknn/index.rst
docs/source/onnx/rknn/install.rst
docs/source/onnx/rknn/models.rst

See https://k2-fsa.github.io/sherpa/onnx/rknn/index.html

Add doc for RKNN

---

docs/source/onnx/android/build-sherpa-onnx.rst
docs/source/onnx/pretrained_models/offline-transducer/code-zipformer/sherpa-onnx-zipformer-vi-2025-04-20.txt
docs/source/onnx/pretrained_models/offline-transducer/code-zipformer/sherpa-onnx-zipformer-vi-int8-2025-04-20.txt
docs/source/onnx/pretrained_models/offline-transducer/zipformer-transducer-models.rst

Please see
https://k2-fsa.github.io/sherpa/onnx/pretrained_models/index.html
https://k2-fsa.github.io/sherpa/onnx/pretrained_models/offline-transducer/zipformer-transducer-models.html#sherpa-onnx-zipformer-vi-2025-04-20-vietnamese
---
see also
https://huggingface.co/zzasdf/viet_iter3_pseudo_label

Add onnx models for Vietnamese

---

.github/workflows/build-doc.yml
.github/workflows/pdf-doc.yml
docs/source/conf.py
docs/source/cpp/pretrained_models/index.rst
docs/source/ncnn/android/build-sherpa-ncnn.rst
docs/source/ncnn/install/riscv64-embedded-linux.rst
docs/source/onnx/android/build-sherpa-onnx.rst
docs/source/onnx/c-api/index.rst
docs/source/onnx/csharp-api/index.rst
docs/source/onnx/go-api/index.rst
docs/source/onnx/harmony-os/how-to-build-har.rst
docs/source/onnx/install/aarch64-embedded-linux.rst
docs/source/onnx/install/arm-embedded-linux.rst
docs/source/onnx/install/riscv64-embedded-linux.rst
docs/source/onnx/pascal-api/index.rst
docs/source/onnx/pretrained_models/wenet/all-models.rst
docs/source/onnx/pretrained_models/whisper/colab.rst
docs/source/onnx/pretrained_models/whisper/export-onnx.rst
docs/source/onnx/pretrained_models/whisper/large-v3.rst
docs/source/onnx/python/non-streaming-websocket-server.rst
docs/source/onnx/python/streaming-websocket-server.rst
docs/source/onnx/speaker-diarization/models.rst
docs/source/onnx/tts/wasm/index.rst
docs/source/onnx/wasm/index.rst
docs/source/pdf.rst
docs/source/python/offline_asr/conformer/aishell.rst
docs/source/python/offline_asr/conformer/librispeech.rst
docs/source/python/offline_asr/standalone/transducer.rst
docs/source/sherpa/pretrained_models/index.rst

Support building pdf doc containing Chinese.

---

docs/source/onnx/index.rst
docs/source/onnx/source-separation/hf.rst
docs/source/onnx/source-separation/index.rst
docs/source/onnx/source-separation/models.rst
docs/source/onnx/tts/hf-space.rst
docs/source/onnx/tts/pretrained_models/kokoro.rst

Please see
https://k2-fsa.github.io/sherpa/onnx/source-separation/index.html

Add doc for source separation

---

docs/source/onnx/android/build-sherpa-onnx.rst
docs/source/onnx/c-api/index.rst
docs/source/onnx/harmony-os/how-to-build-har.rst
docs/source/onnx/install/aarch64-embedded-linux.rst
docs/source/onnx/install/arm-embedded-linux.rst
docs/source/onnx/install/riscv64-embedded-linux.rst
docs/source/onnx/install/windows.rst
docs/source/onnx/java-api/build-jar.rst
docs/source/onnx/java-api/build-jni-linux.rst
docs/source/onnx/java-api/build-jni-macos.rst
docs/source/onnx/java-api/build-jni-windows.rst
docs/source/onnx/punctuation/pretrained_models.rst
docs/source/onnx/tts/piper.rst

Please see
https://k2-fsa.github.io/sherpa/onnx/punctuation/index.html

Update doc for punctuation models

---

docs/source/conf.py
docs/source/onnx/vad/index.rst
docs/source/onnx/vad/silero-vad.rst
docs/source/onnx/vad/ten-vad.rst

Please see
https://k2-fsa.github.io/sherpa/onnx/vad/index.html

Update doc for vad

---

.github/workflows/build-doc.yml
docs/source/onnx/tts/pretrained_models/kitten.rst
docs/source/onnx/tts/pretrained_models/kokoro.rst

See also
https://k2-fsa.github.io/sherpa/onnx/tts/all/English/kitten-en-v0_1.html

Add audio samples for KittenTTS models to doc
